sudo: false
language: python

python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.9.*
  - DJANGO_VERSION=1.10.*
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=1.11.*

install:
  - pip install Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install coveralls

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W ipware; fi

matrix:
  exclude:
   - python: 3.3
     env: DJANGO_VERSION=1.9.*
   - python: 3.3
     env: DJANGO_VERSION=1.10.*
   - python: 3.3
     env: DJANGO_VERSION=1.11
   - python: 3.3
     env: DJANGO_VERSION=1.11.*

script: coverage run --source=ipware manage.py test

after_success:
  coveralls

